# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-07 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='answer_answer_by', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='answer',
            name='parent',
            field=models.ForeignKey(blank=True, help_text=b'User can reply on the answer as well', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='answer_parent',
                                    to='core.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(help_text=b'Each question can have multiple answers', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='question_answer',
                                    to='core.Answer'),
        ),
        migrations.AddField(
            model_name='question',
            name='asked_by',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                       related_name='question_asked_by', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(help_text=b'Tag that suits the category of a question',
                                         related_name='question_tag', to='core.Tag'),
        ),
    ]
