# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-08 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190107_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reputation',
            field=models.IntegerField(default=1, verbose_name=b'Reputation'),
        ),
        migrations.AddField(
            model_name='answer',
            name='favourite',
            field=models.BooleanField(default=False, help_text=b'User can like the answer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name=b'Up-vote/Down-vote'),
        ),
    ]
