# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190108_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
        migrations.AddField(
            model_name='answer',
            name='down_vote',
            field=models.IntegerField(default=0, verbose_name=b'Up-vote'),
        ),
        migrations.AddField(
            model_name='answer',
            name='up_vote',
            field=models.IntegerField(default=0, verbose_name=b'Up-vote'),
        ),
        migrations.AddField(
            model_name='question',
            name='down_vote',
            field=models.IntegerField(default=0, verbose_name=b'Up-vote'),
        ),
        migrations.AddField(
            model_name='question',
            name='up_vote',
            field=models.IntegerField(default=0, verbose_name=b'Up-vote'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answer_answer_by', to='core.Profile'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='favourite',
            field=models.IntegerField(default=0, help_text=b'User can like the answer'),
        ),
        migrations.AlterField(
            model_name='question',
            name='asked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_asked_by', to='core.Profile'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ManyToManyField(blank=True, help_text=b'Each question can have multiple answers',
                                         related_name='question_answer', to='core.Answer'),
        ),
    ]
