# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-09 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190109_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='reputation',
        ),
        migrations.AddField(
            model_name='profile',
            name='reputation',
            field=models.IntegerField(default=0, verbose_name=b'Reputation'),
        ),
    ]
